M48
; DRILL file {KiCad 7.0.1} date Wed Oct 11 20:36:58 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-11T20:36:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X232.222Y-42.564
X232.222Y-48.564
T2
X188.417Y-66.802
X188.977Y-22.213
X231.537Y-67.632
T0
M30
